### ISSUE TITLE
[Bug]: when milvus service is down, search will retry many times. It will result the client wail for a long time, but got a timeout exception in the end.

### ISSUE THREAD

**Issue by micronetboy** [milvus-io/pymilvus#1848] opened 2024-01-04 07:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when milvus service is down, search will retry many times，finally return timeout。It will result the client wail for a long time, but got a timeout exception in the end.

I want it fast fail. No retry.

This is my search code:
collection.search(vectors_to_search, "embedding", search_params, expr=exp, limit=3, output_fields=["user_msg","npc_msg"], timeout=0.2)

### Expected Behavior

I want it fast fail. No retry.

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by cstub** [comment] 2024-01-05 10:34
I think this is caused by the retry behaviour implemented in https://github.com/milvus-io/pymilvus/blob/d91038798b02c1cf7708d672bf9ac94789467334/pymilvus/decorators.py#L48C13-L48C101
which only applies the supplied timeout to retries if the timeout is an `int` variable.

I don't fully understand why the supplied timeout has to be an `int` to be applicable for retries, given that the public APIs (search, insert, upsert...) specify the timeout as a `float` parameter. This means that the retry behaviour changes depending on the provided datatype (`int`  or `float`).

Can anyone shed some light on this issue please?

**Comment by micronetboy** [comment] 2024-01-08 03:40
Could we have a retry_times parameter to specify no retry in vector search?

**Comment by XuanYang-cn** [comment] 2024-03-05 09:33
close this for retry_times was supported by #1826 

@micronetboy feel free to reopen this issue

**Closed by XuanYang-cn** 2024-03-05 09:33 UTC
